### ISSUE TITLE
Hacksessions organising checklist

### ISSUE THREAD

**Issue by crangelsmith** [alan-turing-institute/hut23-open-source-sa#20]
# Overview

REG runs monthly sessions where we come together and contribute to upstream open-source repositories. The sessions take place 2-5 pm every third Friday of the month. The organisation of these sessions are done in the #hut23-hacksession-organising slack channel, a public channel #open-source-hacksessions is available for announcements and running the session. 

Zoom link can be found in the calendar event.

On the first Monday of the month, a reminder will be sent to #hut23-hacksession-organising asking for a volunteer organiser. We should have a rotation to share the work.

__Organisers should copy/paste the checklist below__

```
-  [ ] Create a new issue with the date of the hack session and copy this checklist. This issue will document the full session. Assing issue to the person organising that month.
- [ ] Check Turing meeting room is booked (should be Cipher - check the cipher meeting room calendar not the meeting invite as sometime it says accepted but isn't).
- [ ] Check that the Slack workflow for advertising is doing its thing (reminders should go out a week before and the day of)
- [ ] Run the event
- [ ] Collect contributions to the session in the issue relevant to the session.
- [ ] Update the main page with new contributions https://github.com/alan-turing-institute/research-engineering-group/wiki/Open-source-hacksessions
```

**Comment by mhauru** [comment]
New checklist now that we have Slack automation:

-  [ ] Create a new issue with the date of the hack session and copy this checklist. This issue will document the full session. Assing issue to the person organising that month.
- [ ] Check Turing meeting room is booked (should be Cipher).
- [ ] Check that the Slack workflow for advertising is doing its thing (reminders should go out a week before and the day of)
- [ ] Run the event
- [ ] Collect contributions to the session in the issue relevant to the session.
- [ ] Update the main page with new contributions https://github.com/alan-turing-institute/research-engineering-group/wiki/Open-source-hacksessions

**Comment by rwood-97** [comment]
TODO: Update this with new website
